// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": process.env.aws_cognito_identity_pool_id,
    "aws_cognito_region": "us-west-2",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
